# Generated by Django 3.0.5 on 2020-04-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('confirmed_cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
