# Generated by Django 3.0.5 on 2020-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_consolidateddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeWiseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=100)),
                ('cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('mortality', models.FloatField(default=0.0)),
                ('as_of_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ComparisionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('world', models.CharField(max_length=100)),
                ('india', models.CharField(max_length=100)),
                ('maharashtra', models.CharField(max_length=100)),
                ('as_of_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StateWiseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('mortality', models.FloatField(default=0.0)),
                ('as_of_date', models.DateTimeField()),
            ],
        ),
    ]
